# Generated by Django 3.2.5 on 2022-11-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalReport', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('lineNumber', models.CharField(default='1', max_length=1)),
                ('stationName', models.CharField(default='', max_length=10)),
                ('stationNum', models.CharField(default='000', max_length=3, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timeTable', models.JSONField(default={'arrivalTime': [], 'departureTime': []})),
                ('reported', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='홍길동', max_length=20)),
                ('Password', models.CharField(default='password', max_length=20)),
                ('Reported', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleName', models.CharField(default='My Schedule', help_text='Name of the Schedule', max_length=30)),
                ('routeContent', models.JSONField(default={'end': '', 'start': '', 'waypoint': []})),
                ('week', models.CharField(choices=[('mon', '월요일'), ('tue', '화요일'), ('wed', '수요일'), ('thu', '목요일'), ('fri', '금요일'), ('sat', '토요일'), ('son', '일요일')], default='', max_length=3)),
                ('time', models.CharField(default='00:00:00', max_length=10)),
                ('count', models.SmallIntegerField(default=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favStationName', models.CharField(default='', max_length=10)),
                ('favstationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Favorite Route', max_length=30)),
                ('content', models.JSONField(default={'end': '', 'start': '', 'waypoint': []})),
                ('favRouteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.user')),
            ],
        ),
    ]
