# Generated by Django 3.2.5 on 2022-11-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
