# Generated by Django 3.2.5 on 2022-11-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20221118_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='station',
            name='transfer',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
